# 回答
---

- 作業ディレクトリは`gnn/src/`

In [21]:
import numpy as np
from sklearn.model_selection import train_test_split
from data_loader import *
from util import *
from model import GNN

## task1
---
- Aggregateレイヤーを作る

In [30]:
X_test = [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0]]
W_test = np.random.normal(0, 0.4, (8, 8))

Aggregate_t_times(W_test, X_test, embed_dim=8)

array([ 9.67253642,  0.        ,  5.05628561,  0.        ,  0.        ,
        0.        ,  0.        , 12.33670687])

In [31]:
W_test

array([[ 4.72433702e-01, -3.67174455e-01,  2.86394659e-01,
        -2.22906653e-01, -5.16707164e-01,  1.39077385e-01,
        -4.88969207e-01, -4.90495448e-01],
       [-2.97350123e-01,  4.25395454e-02, -1.74842346e-01,
        -1.78118747e-02, -3.49057744e-01,  1.65135967e-01,
        -1.44099253e-01, -5.83406539e-01],
       [ 4.27652059e-01, -5.18079690e-02, -4.33686215e-01,
        -1.02248016e+00,  7.36097566e-02,  5.28856904e-01,
         3.82132516e-01,  2.42991030e-01],
       [-3.04944382e-01, -1.76802342e-01, -2.67764783e-01,
         7.00628837e-02, -1.48096137e-01,  2.58598037e-01,
         2.85644786e-01,  2.66523414e-01],
       [-6.43599434e-01,  5.00058924e-05, -3.27804624e-02,
        -9.36470268e-02, -2.39637899e-01, -7.62901031e-01,
         4.54225473e-01,  6.79585403e-02],
       [-2.76308660e-01,  3.84258506e-01, -3.49533192e-01,
        -4.05345880e-01,  2.88040847e-01, -2.40170857e-01,
        -1.96348230e-02,  2.68767336e-02],
       [ 2.57358732e-01,  3.752069

## task2
---
- 適当な1つのグラフを使ってモデルを学習させる

In [20]:
# a graph
X_test = [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0]]
y_test = 0

gnn = GNN()
optimizer = 'SGD'
gnn.train([X_test], [y_test], epoch=50, minibatch=1, optimizer=optimizer)

epoch: 1 loss: 0.6829250875004971
epoch: 2 loss: 0.6613333568088632
epoch: 3 loss: 0.6407310853866756
epoch: 4 loss: 0.6210684320284763
epoch: 5 loss: 0.6022976401425328
epoch: 6 loss: 0.5843730501799284
epoch: 7 loss: 0.5672510922161004
epoch: 8 loss: 0.5508902619133722
epoch: 9 loss: 0.5352510828128231
epoch: 10 loss: 0.5202960576089795
epoch: 11 loss: 0.5059896107638915
epoch: 12 loss: 0.4922980245277561
epoch: 13 loss: 0.4791893701580251
epoch: 14 loss: 0.4666334358725363
epoch: 15 loss: 0.45460165283720144
epoch: 16 loss: 0.44306702027657535
epoch: 17 loss: 0.43200403060630754
epoch: 18 loss: 0.4213885953195467
epoch: 19 loss: 0.4111979722136325
epoch: 20 loss: 0.4014106944174534
epoch: 21 loss: 0.39200650157194866
epoch: 22 loss: 0.3829662734246448
epoch: 23 loss: 0.37427196602211554
epoch: 24 loss: 0.36590655062003963
epoch: 25 loss: 0.3578539553776146
epoch: 26 loss: 0.3500990098598467
epoch: 27 loss: 0.3426273923364361
epoch: 28 loss: 0.33542557983829113
epoch: 29 loss: 0.3284

In [32]:
gnn.predict([X_test])

array([0])

In [33]:
gnn.forward([X_test])

0.0

In [34]:
del gnn

## task3,4
---
- データセットを使って学習させる

- データセットを読み込んで，train / testで分割

In [2]:
# create datasets
X, y = load_train()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

- 早速学習（ためしに10エポック）

In [3]:
# train
gnn = GNN()
optimizer = 'Momentum'
gnn.train(X_train, y_train, epoch=10, minibatch=128, optimizer=optimizer)

epoch: 1 loss: 12.104313437898142
epoch: 2 loss: 12.064583526145102
epoch: 3 loss: 11.811866058927045
epoch: 4 loss: 11.63484356880058
epoch: 5 loss: 11.231537437211431
epoch: 6 loss: 11.407809567235375
epoch: 7 loss: 11.44997109212933
epoch: 8 loss: 11.15206860127311
epoch: 9 loss: 10.942713282299263
epoch: 10 loss: 10.920001509676723


- とりあえずテスト

In [4]:
# test
y_hat = gnn.predict(X_test)
correct = 0
for i in range(len(y_test)):
    if y_hat[i] == y_test[i]:
        correct += 1
print("acc: ", correct / len(y_test))

acc:  0.49166666666666664


In [5]:
y_hat

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

- これ大丈夫か...?
- 学習回数増やしてみて...

In [6]:
gnn.A

array([-0.02210262, -0.05980579, -0.6135799 ,  0.29667731,  1.02953733,
        0.42028113, -0.41596161,  0.25077327])

In [7]:
gnn.W

array([[ 0.23765164,  0.09250657,  0.18536218, -0.09355272, -0.6245136 ,
         0.19822734,  0.63767665,  0.39551303],
       [ 0.2825603 , -0.88064451,  0.40177078,  0.57679517,  0.37040268,
        -0.82485713,  0.39650593,  0.02293656],
       [-0.63309941,  0.3507792 ,  0.11349525, -0.01986282,  0.26066349,
         0.02126467, -0.47739683,  0.04436839],
       [ 0.25877959,  0.05548808, -0.22586903,  0.95856604,  0.02195852,
        -0.73442048,  0.12318289, -0.72006328],
       [-0.08341933,  0.16595626,  0.30591345, -0.34464139,  0.44520154,
        -0.50810076,  0.49973899,  0.29358838],
       [-0.60570758,  0.03524601, -0.52241988, -0.20276247, -0.79651846,
        -0.43872529, -0.14984155, -0.17166178],
       [ 0.83817434, -0.03354982,  0.21736043,  0.46973116,  0.05088508,
        -0.38623889, -0.32842978, -0.24474591],
       [ 0.07361457, -0.04777084, -0.34351133,  0.00383728,  0.09373888,
        -0.36331159,  0.05875661,  0.70372873]])